/**
 * Top-level modules of the Python standard library: `sys.stdlib_module_names`
 * of CPython 3.14, plus `__future__` and `_thread`, plus modules removed in
 * 3.12 and 3.13 that older code still imports. An import of one of these is
 * the standard library unless the repository defines a module of that name.
 */
export const PYTHON_STDLIB: ReadonlySet<string> = new Set([
  'abc',
  'annotationlib',
  'antigravity',
  'argparse',
  'array',
  'ast',
  'asyncio',
  'atexit',
  'base64',
  'bdb',
  'binascii',
  'bisect',
  'builtins',
  'bz2',
  'cProfile',
  'calendar',
  'cmath',
  'cmd',
  'code',
  'codecs',
  'codeop',
  'collections',
  'colorsys',
  'compileall',
  'compression',
  'concurrent',
  'configparser',
  'contextlib',
  'contextvars',
  'copy',
  'copyreg',
  'csv',
  'ctypes',
  'curses',
  'dataclasses',
  'datetime',
  'dbm',
  'decimal',
  'difflib',
  'dis',
  'doctest',
  'email',
  'encodings',
  'ensurepip',
  'enum',
  'errno',
  'faulthandler',
  'fcntl',
  'filecmp',
  'fileinput',
  'fnmatch',
  'fractions',
  'ftplib',
  'functools',
  'gc',
  'genericpath',
  'getopt',
  'getpass',
  'gettext',
  'glob',
  'graphlib',
  'grp',
  'gzip',
  'hashlib',
  'heapq',
  'hmac',
  'html',
  'http',
  'idlelib',
  'imaplib',
  'importlib',
  'inspect',
  'io',
  'ipaddress',
  'itertools',
  'json',
  'keyword',
  'linecache',
  'locale',
  'logging',
  'lzma',
  'mailbox',
  'marshal',
  'math',
  'mimetypes',
  'mmap',
  'modulefinder',
  'msvcrt',
  'multiprocessing',
  'netrc',
  'nt',
  'ntpath',
  'nturl2path',
  'numbers',
  'opcode',
  'operator',
  'optparse',
  'os',
  'pathlib',
  'pdb',
  'pickle',
  'pickletools',
  'pkgutil',
  'platform',
  'plistlib',
  'poplib',
  'posix',
  'posixpath',
  'pprint',
  'profile',
  'pstats',
  'pty',
  'pwd',
  'py_compile',
  'pyclbr',
  'pydoc',
  'pydoc_data',
  'pyexpat',
  'queue',
  'quopri',
  'random',
  're',
  'readline',
  'reprlib',
  'resource',
  'rlcompleter',
  'runpy',
  'sched',
  'secrets',
  'select',
  'selectors',
  'shelve',
  'shlex',
  'shutil',
  'signal',
  'site',
  'smtplib',
  'socket',
  'socketserver',
  'sqlite3',
  'sre_compile',
  'sre_constants',
  'sre_parse',
  'ssl',
  'stat',
  'statistics',
  'string',
  'stringprep',
  'struct',
  'subprocess',
  'symtable',
  'sys',
  'sysconfig',
  'syslog',
  'tabnanny',
  'tarfile',
  'tempfile',
  'termios',
  'textwrap',
  'this',
  'threading',
  'time',
  'timeit',
  'tkinter',
  'token',
  'tokenize',
  'tomllib',
  'trace',
  'traceback',
  'tracemalloc',
  'tty',
  'turtle',
  'turtledemo',
  'types',
  'typing',
  'unicodedata',
  'unittest',
  'urllib',
  'uuid',
  'venv',
  'warnings',
  'wave',
  'weakref',
  'webbrowser',
  'winreg',
  'winsound',
  'wsgiref',
  'xml',
  'xmlrpc',
  'zipapp',
  'zipfile',
  'zipimport',
  'zlib',
  'zoneinfo',
  // Removed from the standard library in 3.12 and 3.13.
  'aifc',
  'asynchat',
  'asyncore',
  'audioop',
  'cgi',
  'cgitb',
  'chunk',
  'crypt',
  'distutils',
  'imghdr',
  'imp',
  'lib2to3',
  'mailcap',
  'msilib',
  'nis',
  'nntplib',
  'ossaudiodev',
  'pipes',
  'smtpd',
  'sndhdr',
  'spwd',
  'sunau',
  'telnetlib',
  'uu',
  'xdrlib',
  '__future__',
  '_thread',
]);

/**
 * Well-known distributions whose import name differs from their PyPI name
 * (`import yaml` is PyYAML). An import resolves to one of these only when the
 * project declares that distribution.
 */
export const PYTHON_IMPORT_DISTRIBUTIONS: Readonly<Record<string, readonly string[]>> = {
  Bio: ['biopython'],
  Crypto: ['pycryptodome', 'pycrypto'],
  Cryptodome: ['pycryptodomex'],
  Levenshtein: ['python-Levenshtein', 'Levenshtein'],
  MySQLdb: ['mysqlclient'],
  OpenGL: ['PyOpenGL'],
  OpenSSL: ['pyOpenSSL'],
  PIL: ['Pillow', 'PIL'],
  attr: ['attrs'],
  bs4: ['beautifulsoup4'],
  cv2: ['opencv-python', 'opencv-python-headless', 'opencv-contrib-python'],
  dateutil: ['python-dateutil'],
  dns: ['dnspython'],
  docx: ['python-docx'],
  dotenv: ['python-dotenv'],
  faiss: ['faiss-cpu', 'faiss-gpu'],
  fitz: ['PyMuPDF'],
  gi: ['PyGObject'],
  git: ['GitPython'],
  grpc: ['grpcio'],
  jose: ['python-jose'],
  jwt: ['PyJWT'],
  kafka: ['kafka-python'],
  ldap: ['python-ldap'],
  magic: ['python-magic'],
  mpl_toolkits: ['matplotlib'],
  multipart: ['python-multipart'],
  nacl: ['PyNaCl'],
  pkg_resources: ['setuptools'],
  pptx: ['python-pptx'],
  psycopg2: ['psycopg2', 'psycopg2-binary'],
  pythoncom: ['pywin32'],
  ruamel: ['ruamel.yaml'],
  serial: ['pyserial'],
  skimage: ['scikit-image'],
  sklearn: ['scikit-learn'],
  slugify: ['python-slugify'],
  socks: ['PySocks'],
  telegram: ['python-telegram-bot'],
  usb: ['pyusb'],
  win32api: ['pywin32'],
  win32con: ['pywin32'],
  wx: ['wxPython'],
  yaml: ['PyYAML'],
  zmq: ['pyzmq'],
};
